# Generated by Django 5.1.1 on 2024-12-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_alter_categoria_options_and_more'),
        ('fornecedor', '0002_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('idRequisicao', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('codigoDeBarras', models.CharField(blank=True, max_length=255, null=True)),
                ('dataSolicitacao', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('idFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
            ],
            options={
                'ordering': ['-nomeProduto'],
            },
        ),
    ]
