# Generated by Django 5.1.1 on 2024-10-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-nomeCategoria']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nomeCategoria',
        ),
    ]
