# Generated by Django 5.1.1 on 2024-10-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['-nomeFornecedor']},
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='nomeFornecedor',
        ),
    ]
