# Generated by Django 5.1.1 on 2024-10-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0009_alter_produto_codigodebarras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaSaida',
            fields=[
                ('idEntradaSaida', models.AutoField(primary_key=True, serialize=False)),
                ('entradaSaida', models.CharField(default='E', max_length=1)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'ordering': ['-idProduto'],
            },
        ),
    ]
