# Generated by Django 5.1.1 on 2024-10-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradaSaida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradasaida',
            options={'ordering': ['-descricao']},
        ),
        migrations.AddField(
            model_name='entradasaida',
            name='descricao',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
