# Generated by Django 5.1.1 on 2024-10-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradaSaida', '0002_alter_entradasaida_options_entradasaida_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='entradaSaida',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1),
        ),
    ]
