# Generated by Django 5.1.1 on 2024-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradaSaida', '0003_alter_entradasaida_entradasaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
