# Generated by Django 5.1.1 on 2024-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('idCategoria', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=0)),
                ('idFornecedor', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigoDeBarras', models.CharField(max_length=255)),
                ('dataEntrada', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-nome'],
            },
        ),
    ]
