# Generated by Django 5.1.1 on 2024-10-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_idfornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-nomeProduto']},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nomeProduto',
        ),
    ]
