# Generated by Django 5.1.1 on 2024-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_datavencimento_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dataVencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
