# Generated by Django 5.1.1 on 2024-10-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_datavencimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dataVencimento',
            new_name='dataValidade',
        ),
    ]
