# Generated by Django 5.1.1 on 2024-10-28 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_rename_datavencimento_produto_datavalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dataValidade',
            field=models.DateField(blank=True, db_default=datetime.date(2024, 10, 28), null=True),
        ),
    ]
