# Generated by Django 5.1.1 on 2024-10-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_options_and_more'),
        ('fornecedor', '0002_alter_fornecedor_options_and_more'),
        ('produto', '0008_alter_produto_datavalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigoDeBarras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='idFornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
