# Generated by Django 5.1.1 on 2024-12-12 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_codigodebarras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dataValidade',
            field=models.DateField(blank=True, db_default=datetime.date(2024, 12, 12), null=True),
        ),
    ]
